AllCops:
  Excludes:
    - db/schema.rb
  Rails:
    Enabled: true
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 23

Documentation:
  Enabled: false
