AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 40

Documentation:
  Enabled: false
