default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lunch_buddy_development

test:
  <<: *default
  database: lunch_buddy_test


production:
  <<: *default
  database: lunch_buddy_production
